# Generated by Django 4.2.7 on 2025-10-22 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, max_length=200)),
                ('anthropic_api_key', models.CharField(blank=True, max_length=200)),
                ('google_ai_api_key', models.CharField(blank=True, max_length=200)),
                ('default_model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('default_temperature', models.FloatField(default=0.7)),
                ('default_max_tokens', models.IntegerField(default=1000)),
                ('monthly_request_limit', models.IntegerField(default=100)),
                ('daily_request_limit', models.IntegerField(default=10)),
                ('cost_limit_per_month', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('content_generation_enabled', models.BooleanField(default=True)),
                ('image_generation_enabled', models.BooleanField(default=False)),
                ('code_generation_enabled', models.BooleanField(default=False)),
                ('seo_optimization_enabled', models.BooleanField(default=True)),
                ('enable_content_review', models.BooleanField(default=True)),
                ('auto_save_generated_content', models.BooleanField(default=True)),
                ('enable_version_control', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('output_text', models.TextField(blank=True)),
                ('output_files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=8)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tool_type', models.CharField(choices=[('content_generator', 'Content Generator'), ('image_generator', 'Image Generator'), ('seo_optimizer', 'SEO Optimizer'), ('text_improver', 'Text Improver'), ('translator', 'Translator'), ('code_generator', 'Code Generator'), ('design_assistant', 'Design Assistant')], max_length=30)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('requires_api_key', models.BooleanField(default=True)),
                ('cost_per_request', models.DecimalField(decimal_places=4, default=0.001, max_digits=6)),
                ('max_requests_per_hour', models.IntegerField(default=100)),
                ('max_requests_per_day', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('blog', 'Blog Posts'), ('product', 'Product Descriptions'), ('service', 'Service Pages'), ('about', 'About Us'), ('landing', 'Landing Pages'), ('email', 'Email Marketing'), ('social', 'Social Media'), ('seo', 'SEO Content')], max_length=20)),
                ('description', models.TextField()),
                ('prompt_template', models.TextField()),
                ('example_output', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'Text Content'), ('html', 'HTML Content'), ('css', 'CSS Styles'), ('javascript', 'JavaScript Code'), ('json', 'JSON Data')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_in_page', models.CharField(blank=True, max_length=100)),
                ('used_in_component', models.CharField(blank=True, max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('seo_score', models.FloatField(blank=True, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to='ai_tools.airequest')),
                ('parent_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_tools.generatedcontent')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_tools.contenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='airequest',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ai_tools.aitool'),
        ),
        migrations.CreateModel(
            name='AIUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('avg_processing_time', models.FloatField(default=0.0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('top_prompts', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='ai_tools.aitool')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'tool')},
            },
        ),
    ]
